import { HttpError } from '../utils/http-error.js';
function date(value) { if (value === null || value === undefined || value === '') return null; const parsed = new Date(`${value}T00:00:00.000Z`); if (Number.isNaN(parsed.getTime()) || parsed > new Date()) throw new HttpError(422, 'La fecha de nacimiento no es válida'); return parsed; }
function paidUntilDate(value) { if (value === null || value === undefined || value === '') return null; const parsed = new Date(value); if (Number.isNaN(parsed.getTime())) throw new HttpError(422, 'paidUntil no es una fecha válida'); return parsed; }
// Mismo rango que el OVR calculado (calculateOverall/calculateGoalkeeperOverall
// en el frontend siempre devuelven entre 60 y 99), para que un OVR fijo no
// rompa visualmente la tarjeta con un valor fuera de escala.
function fixedOvrValue(value) { if (value === null || value === undefined || value === '') return null; const parsed = Number(value); if (!Number.isInteger(parsed) || parsed < 60 || parsed > 99) throw new HttpError(422, 'fixedOvr debe ser un entero entre 60 y 99'); return parsed; }
function fields(body, file, partial) { const data = {}; if (!partial || body.name !== undefined) { const name = String(body.name ?? '').trim(); if (!name || name.length > 120) throw new HttpError(422, 'El nombre es obligatorio y debe tener máximo 120 caracteres'); data.name = name; } if (body.birthDate !== undefined) data.birthDate = date(body.birthDate); if (body.documentNumber !== undefined) data.documentNumber = String(body.documentNumber).trim() || null; if (body.jerseyNumber !== undefined) data.jerseyNumber = String(body.jerseyNumber).trim().slice(0, 10) || null; if (body.paidUntil !== undefined) data.paidUntil = paidUntilDate(body.paidUntil); if (body.fixedOvr !== undefined) data.fixedOvr = fixedOvrValue(body.fixedOvr); if (body.status !== undefined) { if (!['ACTIVE', 'DISABLED'].includes(body.status)) throw new HttpError(422, 'Estado no válido'); data.status = body.status; } if (file) data.photo = `/uploads/players/${file.filename}`; return data; }
export function validateCreatePlayer(request, _response, next) { try { request.validatedBody = fields(request.body ?? {}, request.file, false); return next(); } catch (error) { return next(error); } }
export function validateUpdatePlayer(request, _response, next) { try { const data = fields(request.body ?? {}, request.file, true); if (!Object.keys(data).length) throw new HttpError(422, 'No hay cambios para guardar'); request.validatedBody = data; return next(); } catch (error) { return next(error); } }
export function validateSetGoalkeeper(request, _response, next) { try { if (typeof request.body?.isGoalkeeper !== 'boolean') throw new HttpError(422, 'isGoalkeeper debe ser verdadero o falso'); request.validatedBody = { isGoalkeeper: request.body.isGoalkeeper }; return next(); } catch (error) { return next(error); } }
export function validateSetShowName(request, _response, next) { try { if (typeof request.body?.showName !== 'boolean') throw new HttpError(422, 'showName debe ser verdadero o falso'); request.validatedBody = { showName: request.body.showName }; return next(); } catch (error) { return next(error); } }
